### ISSUE TITLE
spin up stage instance of triannon

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/triannon-service#10]
_From @ndushay on February 27, 2015 21:10_

need VMs:
- [x] sul-fedora-stage box?
- [x] triannon-stage box

Additionally:
- [x] sul-solr collection/core  sul-dlss/sul-solr-configs/pull/11
- [x] cap deploy stage working
- [ ] nagios monitoring?
- [ ] security?
- [ ] squash?
- [ ] robustify netwrk connections?

_Copied from original issue: sul-dlss/triannon#119_

**Comment by ndushay** [comment]
```
Date: March 11, 2015 at 2:17:57 PM PDT
From: Rob Sanderson <azaroth@stanford.edu>
To: Erin Fahy <efahy@stanford.edu>, Naomi Dushay <ndushay@stanford.edu>, Joshua Greben <jgreben@stanford.edu>
Cc: Ben Albritton <blalbrit@stanford.edu>, Stuart Snydman <snydman@stanford.edu>
Subject: Fedora4 / Triannon boxes

Hi Erin, Naomi, Josh,

<snip>

* A much smaller machine to run Triannon on, that can connect to a Fedora4 box.  Triannon would need to be outside of the firewall to allow external connections, but the Fedora4 box could be inside. triannon-demo.stanford.edu would be a reasonable hostname, in my opinion, but there are some questions as to -demo versus -stage versus -test distinctions that would be good to discuss.

* Said Fedora4 box.  Middle of the road system, just a clone of the existing -dev is probably fine.

<snip>

Thanks!

Rob
```

**Comment by ndushay** [comment]
Spoke to Erin;  Filed a SAR ticket for a sul-fedora-staga-a  box and a separate SAR ticket for triannon-stage-a  box.

Erin's assessment is we may want ultimately to "horizontally scale" fedora and load balance it, so we'll start with one fedora-stage server and see how it goes.  We may want to do similar things for Rails box:  we'll start with one triannon box, and see how it goes.

We further discussed whether to:
1.  have multiple triannon rails apps running on single VM for diff buckets (DMS, Mirador, SearchWorks ...)
2.  have single triannon app manage multiple buckets with routes (e.g. triannon-stage/dms/annotations)
3.  have separate VMs with a single triannon app for each bucket

Thinking about the "horizontal scaling" approach, Erin went for option 2.

**Comment by ndushay** [comment]
Boxes are "done".   
* Still waiting on fedora box having NFS mount (? - ask @eefahy ).   
* Supposedly triannon box is done - will know for sure when deploy is working
* have pull request in for solr core for new triannon.

**Comment by ndushay** [comment]
- [x] can see (empty) fedora-stage/rest via web browser on my laptop
- [x] can see (empty) triannon-stage  solr via web browser on my laptop
- [x] capistrano deploy working for stage
- [ ] triannon stage box can't get to fedora stage box (SAR ticket 2694)
- [x] alias setup for triannon-stage, fedora-stage  (to go to specific box or load balancer)
- [ ] multinode certs so aliases work (SAR ticket 2692)

(need alias so annos created can be for load balanced triannon url, not specific box triannon url)

**Comment by ndushay** [comment]
@eefahy informs me a firewall request has been put in and should be in place Monday 4/20 or so

**Comment by azaroth42** [comment]
Excellent! :)

**Comment by aeschylus** [comment]
Currently testing a little module to make Mirador compatible with triannon. Is triannon-dev going to remain up this evening?

**Comment by ndushay** [comment]
yup!

**Comment by ndushay** [comment]
tried to create root anno from triannon-stage -- seems firewall rules still not fixed ...:

```
[triannon@triannon-stage-a current]$ bundle exec rake triannon:create_root_container 
rake aborted!
Errno::ETIMEDOUT: Connection timed out - connect(2) for "sul-fedora-stage-a.stanford.edu" port 443
/opt/app/triannon/triannon/shared/bundle/ruby/2.1.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:82:in `perform_request'
/opt/app/triannon/triannon/shared/bundle/ruby/2.1.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:40:in `block in call'
/opt/app/triannon/triannon/shared/bundle/ruby/2.1.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
/opt/app/triannon/triannon/shared/bundle/ruby/2.1.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:32:in `call'
/opt/app/triannon/triannon/shared/bundle/ruby/2.1.0/gems/faraday-0.9.1/lib/faraday/request/url_encoded.rb:15:in `call'
/opt/app/triannon/triannon/shared/bundle/ruby/2.1.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
/opt/app/triannon/triannon/shared/bundle/ruby/2.1.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
/opt/app/triannon/triannon/shared/bundle/ruby/2.1.0/gems/faraday-0.9.1/lib/faraday/connection.rb:140:in `head'
/opt/app/triannon/triannon/shared/bundle/ruby/2.1.0/gems/triannon-0.7.2/app/services/triannon/root_annotation_creator.rb:10:in `create'
/opt/app/triannon/triannon/shared/bundle/ruby/2.1.0/gems/triannon-0.7.2/lib/tasks/triannon_tasks.rake:9:in `block (2 levels) in <top (required)>'
Tasks: TOP => triannon:create_root_container
```

**Comment by ndushay** [comment]
adding config/secrets.yml and hopefully that will do it, now that firewall stuff is straightened out between stage and fedora stage.

**Comment by ndushay** [comment]
once triannon.yml  was set up for production env, all was well.  triannon-stage is now running!
