### ISSUE TITLE
What is the anno_root in IIIF terms?

### ISSUE THREAD

**Issue by aeschylus** [sul-dlss/triannon-service#12]
Is there a way to get a list by list id, or by the "within" property on the list? We're doing some layers/transcription-related work and are realising our simpleAnnotationStore backend is not going to support everything we need to do in a spec-compliant way.

**Comment by azaroth42** [comment]
The annotation root is (almost) an LDP container in which the annotations are created.  It maps 1:1 to a real LDP container in Fedora4 at the back end.

It has nothing to do with IIIF's AnnotationLists... so in IIIF terms it's at most a service.
