### ISSUE TITLE
compatibility of rest-client 1.8.0, rest-client-components

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/triannon-service#7]
per Gregg's notes here:  https://github.com/ruby-rdf/json-ld/issues/13

we implemented caching of jsonld contexts using  rack-cache with rest-client.

we have a compatibility problem of rest-client latest version with  rest-client-components (which is old)  with RDF gem.   I used  SKIP_BUNDLE_AUDIT=true  workaround to deploy with rest-client v1.7.3.  

We would like to upgrade rest-client, or take another approach to caching jsonld context.

Darren’s bug report to Gregg on this:   https://github.com/ruby-rdf/rdf/issues/174

Darren’s bug report to rest-client-components:   https://github.com/crohr/rest-client-components/issues/8

@cbeer may try to fork something to fix this.
@darrenleeweber @azaroth42 may be interested.

**Comment by ndushay** [comment]
pull request from cbeer to allow for other http adapters:   ruby-rdf/rdf/pull/175

**Comment by azaroth42** [comment]
Thanks all, this looks very good! Glad that we're able to contribute back to the Ruby/RDF community through this work and I expect that will continue as linked data becomes a stronger infrastructural component in the library! :)

**Comment by ndushay** [comment]
ruby-rdf/rdf#175 is merged.  Wait for new gem release and then use faraday to cache.  Modeled here:

ruby-rdf/rdf/pull/176

**Comment by ndushay** [comment]
See #151.  Gregg's pr  crohr/rest-client-components#9 was included in v1.4.0 of rest-client-components;   a fix was applied to triannon gem but looking into memory caching before cutting new release of triannon.

**Comment by ndushay** [comment]
triannon v0.7.1  addresses this.

**Comment by ndushay** [comment]
addressed by #8 and a deploy.
